language: objective-c
osx_image: xcode7.3
install:
    - sudo gem install cocoapods
    - pod install --verbose --no-repo-update
    - xcodebuild -workspace Libight_iOS.xcworkspace/ -scheme Libight_iOS \
      CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
